version: "2"
services:
  db:
      image: mariadb
      environment:
          - MYSQL_ROOT_PASSWORD=test
          - MYSQL_DATABASE=api
      volumes:
          - ./database:/var/lib/mysql
      ports:
          - 3306:3306
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: api-phpmyadmin
      environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=db
      restart: always
      ports:
          - 8080:80
      volumes:
          - /sessions
      links:
          - db